### ISSUE TITLE
Primative obsession in Video.hpp

### ISSUE THREAD

**Issue by bmb134** [liddyjacob/StreamVideo#7] opened 2017-12-13 19:07 UTC
Opened a new issue1 was closed without being fixed.

Using an int as type of video instead of a subclass is the code smell "Bloaters" primitive obsession.

It needs to be refactored with Extract Subclass

**Comment by oreoeo** [comment] 2017-12-13 19:18
I don't know that we are allowed to make this change because it would involve creating a class hierarchy and modifying code other than the test files.

**Comment by bmb134** [comment] 2017-12-13 19:24
yeah we can do anything as long as we don't add new FILES we are supposed to refactor

**Comment by bmb134** [comment] 2017-12-13 19:33
https://gist.github.com/bmb134/963d9de6313db17b7c42e0df08616386

**Comment by bmb134** [comment] 2017-12-13 19:34
that was what I is what i added in my commit but I cant push

**Comment by bmb134** [comment] 2017-12-13 19:36
Also, remember that you need to edit StreamingActivity.cpp 
this link will be helpful for changing the vector problem in that file
https://stackoverflow.com/questions/29722966/adding-subclass-to-a-base-class-vector

**Comment by bmb134** [comment] 2017-12-13 19:48
the varaible "int episodes" and the function " int getEpisodes() const;" should be moved into the class TVSHOW

**Comment by liddyjacob** [comment] 2017-12-13 20:23
Issue 1 was fixed, I created a constructor which took in a struct called VideoParams. I did not delete the old constructor, which I should have done.

**Comment by oreoeo** [comment] 2017-12-13 21:32
If you think the issue is fixed go ahead and close the issue.

**Comment by liddyjacob** [comment] 2017-12-13 22:07
From what I understand, this is a different issue than issue1. What bmb134 is talking about was not the same thing I was talking about in issue1. 

With this issue, I think that leaving the categories of videos as integers is fine, because there are not enough differences in the types of videos to make a subclass for each type. But we should take a vote.

**Comment by bmb134** [comment] 2017-12-14 03:26
I am just saying it shouldn't be that hard and it is one of the code smells

**Comment by oreoeo** [comment] 2017-12-14 21:30
Abstracting these changes into a hierarchy would require adding functionality to the code given which is not the scope of this project, or allowed.  Therefore, I am closing this issue.

**Closed as completed by oreoeo** 2017-12-14 21:30 UTC

**Comment by bmb134** [comment] 2017-12-15 00:12
The only allowed changes to the code are:

Addition of test cases
Functions in the test files that allow for easier writing of test cases
Named, Fowler refactorings. The name of the refactoring (or refactorings if there is a choice) must be used when discussing the issue
You can add classes. If you create new files, you will have to update the Makefile.

It literally says you can add classes and you can use named Fowler refactoring
